function processResponses(responses) {
  let words = [];

  for (let row in responses) {
    words = [
      ...words,
      ...responses[row]
        .split(" ")
        .filter((x) => x !== "")
        .map((w) => w.toLowerCase()),
    ];
  }
  return words
    .filter(
      (x) =>
        ![
          "el",
          "de",
          "que",
          "ese",
          "los",
          "la",
          "las",
          "y",
          "porque",
          "aveces",
          "por",
          "no",
          "con",
          "en",
          "para",
          "caso",
          "fue",
          "un",
          "mi",
          "mis",
          "me",
          "se",
          "es",
          "hacer",
          "a",
          "una",
          "más",
          "mas",
          "segun",
          "según",
          "era",
          "son",
          "necesario",
          "estas",
          "haces",
          "hagan",
          "mis",
          "eso",
          "haciendo",
          "mía",
          "ya",
          "si",
          "del",
          "muy",
          "veces",
          "vi",
          "falta",
        ].includes(x)
    )
    .join(" ");
}

am4core.ready(function () {
  am4core.useTheme(am4themes_animated);

  var chart = am4core.create("chartdiv", am4plugins_wordCloud.WordCloud);
  var series = chart.series.push(new am4plugins_wordCloud.WordCloudSeries());

  series.accuracy = 4;
  series.step = 15;
  series.rotationThreshold = 0.7;
  series.maxCount = 200;
  series.minWordLength = 2;
  series.labels.template.tooltipText = "{word}: {value}";
  series.fontFamily = "Courier New";
  series.maxFontSize = am4core.percent(30);

  series.text = processResponses([
    "el mostrar ese caso ayuda a que los demás no hagan las cosas por el camino fácil",
    "por mis principios éticos y morales",
    "Por moral y frustración ",
    "Porque era la forma de librarme de un posible daño mayor ",
    "Por que podían repercutir en el bienestar de alguien más o en el desarrollo de la labor de la institución ",
    "Porque considero un deber ciudadano respaldar la integridad de los demás",
    "Porque no estaba de acuerdo",
    "No esta bien ",
    "Porque no es correcto y debe denunciarse cada vez que se presencie ",
    "Porque no me parece correcto lo que hacen",
    "Involucran una falta gravísima",
    "Este caso en mención no porque me enteré mucho después cuando ya no había nada que hacer, pero sí he reportado casos en los que por ejemplo un docente denigra la integridad de un niño o niña, lo he hecho porque estaba en peligro su vida o su dignidad.",
    "Por actuar bien ",
    "Porque debemos de ser mejores seres humanos ",
    "La ética importa ",
    "No sé puede dejar pasar el incumplimiento de las normas eticas",
    "No me gusta la injusticia",
    "Por ética personal y colectiva ",
    "Acoso laboral ",
    "Porque va en contra de mis principios ",
    "Porque la estudiante me informó y era una falta muy grave, y la joven se sentía humillada por la insinuación ",
    "Me parecía necesario puesto que afectaba el entorno laboral ",
    "Por que muchas veces los jefes no aceptan que se digan las cosas por que creen tener la razón ",
    "No lo hice",
    "Por convicción de que se obra mal",
    "Porque fue un acto desleal cinmigo y con mi oficina ",
    "Porque se causa enorme daño directo y a terceros",
    "Porque fue un acto desleal cinmigo y con mi oficina ",
    "No me corresponde hacerlo ",
    "Porque me vi afectada",
    "Porque la falta de ética pasa ha ser una falta de honestidad frente a la situación que se está presentando y eso es segun mis principios no es correcto ser deshonesto con las cosas que haces y aveces son faltas de eticas muy descaradas ",
    "Por proteger a slfuien",
    "Porque la falta de ética pasa ha ser una falta de honestidad frente a la situación que se está presentando y eso es segun mis principios no es correcto ser deshonesto con las cosas que haces y aveces son faltas de eticas muy descaradas ",
    "Me parece falta de respeto y por qué faltó a la ética.",
    "Hacer lo justo",
    "Por respeto, porque son temas normativos que se deben hacer cumplir, por la seguridad e integridad de las personas y mía.",
    "por ética",
    "Porque todos merecemos respeto",
    "Mi etica personal",
    "Por mis principios eticos",
    "No tolero la gente sin escrúpulos ",
    "Por que para el cliente no permitía su total claridad en la compra",
    "No me corresponde hacerlo ",
    "Por qué es lo justo y si no se hace nada esto va a seguir sucediendo ",
    "Por conciencia personal y obligación empresarial. En la empresa para la que trabajo esto es una falta grave, es un orgullo, una satisfacción y una TRANQUILIDAD trabajar en una empresa que ha ganado muchas veces el premio a la compañía más ética en EEUU.",
    "Porque va en contra de mis principios ",
    "Porque creo que el cambio inicia de forma individual y que lograr expandir ese sentimiento depende de todos nosotros.",
    "No es justo que se roben la plata y no hagan las obras que se comprometieron a hacer ",
    "Porque creo que el cambio inicia de forma individual y que lograr expandir ese sentimiento depende de todos nosotros.",
    "porque era bastante injusto con la persona ",
    "Porque me vi afectada",
    "No estoy de acuerdo con hacer las cosas mal",
    "Para que no se natularize estas situaciones que afectan a la sociedad ",
    "Para que no se natularize estas situaciones que afectan a la sociedad ",
    "Me parecía necesario puesto que afectaba el entorno laboral ",
    "Porque algunas son muy descaradas y vulneran los derechos de otras personas.",
    "Porque jugaban con el tiempo y convicción de la gente, en la medida en que los embaucan en una lucha que ellos ya tiene actores, víctimas y victimarios con roles definidos por ese grupo de poder. ",
    "No es justo que se roben la plata y no hagan las obras que se comprometieron a hacer ",
    "Para exponer la verdad del caso y la falta de ética y profesionalismo del tercero",
    "Cuando algo me molesta, si veo que puedo hacer algo para que cambie la situación, lo hago.",
    "Porque comprometía la integridad de alguien más",
    "Por el bienestar de esas personas ",
    "No me gusta pára mí, tampoco para los demás.",
    "Porque era necesario",
    "Por qué lo que no quiero para mi mucho menos para los demas",
    "Por qué esos actos tienen que ser penalizado de otra forma se van a seguir haciendo",
    "Porque afectaba a muchas personas",
    "porque no es correcto dañar a otros",
    "Como en la NATURALEZA, ceno o me comen.",
    "Porque me parece que esta atentando contra la seguridad del paciente ",
    "Porque fue un irrespeto a las diferencias ",
    "Hice el reporte de un problema que me afectó directamente. La respuesta fue que hoy estaba yo y mañana estaba otro.",
    "Porque fue un irrespeto a las diferencias ",
    "Porque no va con mis principios tanto asi que me queje con la gerencia y renuncie ya que era mi Jefe",
  ]);
  var chart2 = am4core.create("chartdiv2", am4plugins_wordCloud.WordCloud);
  var series2 = chart2.series.push(new am4plugins_wordCloud.WordCloudSeries());

  series2.accuracy = 4;
  series2.step = 15;
  series2.rotationThreshold = 0.7;
  series2.maxCount = 200;
  series2.minWordLength = 2;
  series2.labels.template.tooltipText = "{word}: {value}";
  series2.fontFamily = "Courier New";
  series2.maxFontSize = am4core.percent(30);

  series2.text = processResponses([
    "Acoso laboral ",
    "Como en la NATURALEZA, ceno o me comen.",
    "Cuando algo me molesta, si veo que puedo hacer algo para que cambie la situación, lo hago.",
    "el mostrar ese caso ayuda a que los demás no hagan las cosas por el camino fácil",
    "Este caso en mención no porque me enteré mucho después cuando ya no había nada que hacer, pero sí he reportado casos en los que por ejemplo un docente denigra la integridad de un niño o niña, lo he hecho porque estaba en peligro su vida o su dignidad.",
    "Hacer lo justo",
    "Hice el reporte de un problema que me afectó directamente. La respuesta fue que hoy estaba yo y mañana estaba otro.",
    "Involucran una falta gravísima",
    "La ética importa ",
    "Me parece falta de respeto y por qué faltó a la ética.",
    "Me parecía necesario puesto que afectaba el entorno laboral ",
    "Me parecía necesario puesto que afectaba el entorno laboral ",
    "Mi etica personal",
    "No es justo que se roben la plata y no hagan las obras que se comprometieron a hacer ",
    "No es justo que se roben la plata y no hagan las obras que se comprometieron a hacer ",
    "No esta bien ",
    "No estoy de acuerdo con hacer las cosas mal",
    "No lo hice",
    "No me corresponde hacerlo ",
    "No me corresponde hacerlo ",
    "No me gusta la injusticia",
    "No me gusta pára mí, tampoco para los demás.",
    "No sé puede dejar pasar el incumplimiento de las normas eticas",
    "No tolero la gente sin escrúpulos ",
    "Para exponer la verdad del caso y la falta de ética y profesionalismo del tercero",
    "Para que no se natularize estas situaciones que afectan a la sociedad ",
    "Para que no se natularize estas situaciones que afectan a la sociedad ",
    "Por actuar bien ",
    "Por conciencia personal y obligación empresarial. En la empresa para la que trabajo esto es una falta grave, es un orgullo, una satisfacción y una TRANQUILIDAD trabajar en una empresa que ha ganado muchas veces el premio a la compañía más ética en EEUU.",
    "Por convicción de que se obra mal",
    "Por el bienestar de esas personas ",
    "por ética",
    "Por ética personal y colectiva ",
    "Por mis principios eticos",
    "por mis principios éticos y morales",
    "Por moral y frustración ",
    "Por proteger a slfuien",
    "Por qué es lo justo y si no se hace nada esto va a seguir sucediendo ",
    "Por qué esos actos tienen que ser penalizado de otra forma se van a seguir haciendo",
    "Por qué lo que no quiero para mi mucho menos para los demas",
    "Por que muchas veces los jefes no aceptan que se digan las cosas por que creen tener la razón ",
    "Por que para el cliente no permitía su total claridad en la compra",
    "Por que podían repercutir en el bienestar de alguien más o en el desarrollo de la labor de la institución ",
    "Por respeto, porque son temas normativos que se deben hacer cumplir, por la seguridad e integridad de las personas y mía.",
    "Porque afectaba a muchas personas",
    "Porque algunas son muy descaradas y vulneran los derechos de otras personas.",
    "Porque comprometía la integridad de alguien más",
    "Porque considero un deber ciudadano respaldar la integridad de los demás",
    "Porque creo que el cambio inicia de forma individual y que lograr expandir ese sentimiento depende de todos nosotros.",
    "Porque creo que el cambio inicia de forma individual y que lograr expandir ese sentimiento depende de todos nosotros.",
    "Porque debemos de ser mejores seres humanos ",
    "porque era bastante injusto con la persona ",
    "Porque era la forma de librarme de un posible daño mayor ",
    "Porque era necesario",
    "Porque fue un acto desleal cinmigo y con mi oficina ",
    "Porque fue un acto desleal cinmigo y con mi oficina ",
    "Porque fue un irrespeto a las diferencias ",
    "Porque fue un irrespeto a las diferencias ",
    "Porque jugaban con el tiempo y convicción de la gente, en la medida en que los embaucan en una lucha que ellos ya tiene actores, víctimas y victimarios con roles definidos por ese grupo de poder. ",
    "Porque la estudiante me informó y era una falta muy grave, y la joven se sentía humillada por la insinuación ",
    "Porque la falta de ética pasa ha ser una falta de honestidad frente a la situación que se está presentando y eso es segun mis principios no es correcto ser deshonesto con las cosas que haces y aveces son faltas de eticas muy descaradas ",
    "Porque la falta de ética pasa ha ser una falta de honestidad frente a la situación que se está presentando y eso es segun mis principios no es correcto ser deshonesto con las cosas que haces y aveces son faltas de eticas muy descaradas ",
    "Porque me parece que esta atentando contra la seguridad del paciente ",
    "Porque me vi afectada",
    "Porque me vi afectada",
    "porque no es correcto dañar a otros",
    "Porque no es correcto y debe denunciarse cada vez que se presencie ",
    "Porque no estaba de acuerdo",
    "Porque no me parece correcto lo que hacen",
    "Porque no va con mis principios tanto asi que me queje con la gerencia y renuncie ya que era mi Jefe",
    "Porque se causa enorme daño directo y a terceros",
    "Porque todos merecemos respeto",
    "Porque va en contra de mis principios ",
    "Porque va en contra de mis principios ",
  ]);

  var chart3 = am4core.create("chartdiv3", am4plugins_wordCloud.WordCloud);
  var series3 = chart3.series.push(new am4plugins_wordCloud.WordCloudSeries());

  series3.accuracy = 4;
  series3.step = 15;
  series3.rotationThreshold = 0.7;
  series3.maxCount = 200;
  series3.minWordLength = 2;
  series3.labels.template.tooltipText = "{word}: {value}";
  series3.fontFamily = "Courier New";
  series3.maxFontSize = am4core.percent(30);

  series3.text = processResponses([
    "a veces por miedo",
    "Ahorrar problemas ",
    "Corría riesgo, pero apesar todo lo esperaba .",
    "cuando no lo hago es por que son cosas que solo le afectan la conciencia a esa persona",
    'Cuando no tengo las herramientas para cambiar la situación no lo hago (muchas veces resulta siendo que la "víctima" no quiere ser ayudada), me he ganado problemas pendejos por sapo',
    "Cuando son los profesores de uno los que cometen faltas éticas e injusticias, no se puede hacer mucho.",
    "El profesor estaba al tanto de la situación, solamente no quería tomar medidas en el asunto",
    "En la academia: por falta de pruebas y de valor. En el trabajo: por falta de valor y porque involucra a quienes firman mi contrato y cuenta de cobro.",
    "En la cuales creo que mi compañero está en lo correcto ",
    "En mi cosepto, porque es responsabilidad de cada quien como ser humano ",
    "Entiendo a veces los motivos del por qué se hacen las cosas y mientras no damnifiquen a nadie en un grado considerable es pasable",
    "Este fue el caso, ya había pasado un tiempo, ya reportar no valía la pena, además no tenía pruebas. ",
    "Hay departamentos que deben evidenciar las faltas éticas, tomando los correctivos necesarios según las políticas de la compañía para esas faltas.",
    "Hay departamentos que deben evidenciar las faltas éticas, tomando los correctivos necesarios según las políticas de la compañía para esas faltas.",
    "Incomodidad con respecto al tema y miedo al despido ",
    "La indiferencia nuestra con las malas acciones es la que nos tiene como estamos ",
    "La indiferencia nuestra con las malas acciones es la que nos tiene como estamos ",
    "Lo creía necesario pero no pensé que ayudaría ",
    "Mecanismos insuficientes",
    "Miedo",
    "Miedo a al supervisor, sus acciones y a la agresividad de mis compañeros. ",
    "Miedo a que las personas me tildan de chismosa o sapa y me excluyan de trabajos ",
    "Miedo a represalias",
    "Mucho protocolo ",
    "No aplica",
    "No es bien visto por los demás prefieren callar ",
    "No fue una prioridad en ese momento ",
    "No le di mucha importancia ",
    "No le di mucha importancia ",
    "No lo consideré pertinente en el momento, pero debí hacerlo.",
    "No lo sentí como responsabilidad mía el reportarlo ",
    "No me incumbe realmente",
    "No pensé que pudiera hacer nada ",
    "No quise echar al agua a los compañeros de clase.",
    "No se ",
    "No tenía las pruebas creíbles en ese momento ",
    "No tenía pruebas",
    "No tenía pruebas y tampoco era de mi incumbencia",
    "Por evitar conflictos",
    "Por evitar conflictos",
    "Por evitar problemas ",
    "Por miedo",
    "Por miedo",
    "Por miedo ",
    "Por miedo a lo que me pudiera pasar a mi ",
    "Por no entrar en discusiones o conflictos",
    "Por no meterme en problemas con las personas ",
    "Por no quedar mal",
    "Por no ser escuchado o estigmatizado como soplon y adicionalmente perder el empleo.",
    "Por principios",
    "Por que el sistema es difícil de romper.",
    "Por qué las personas son concientes de sus actos y la persona que permite que vayan en contra de su bienestar lo acepta y lo tolera es muy difícil opinar o actuar.",
    "Por qué no considere que fuera determinante para el desarrollo de las actividades ",
    "Por qué se tiene la fama de que el profesor es “intocable” en la facultad y supuse que terminaría perdiendo yo ",
    "Por qué se tiene la fama de que el profesor es “intocable” en la facultad y supuse que terminaría perdiendo yo ",
    "Por ser amigo de alguien ",
    "Por vergüenza ",
    "Por vergüenza ",
    "Porque hay niveles de jerarquía, por lo que puede acarrear consecuencias delatar a los superiores",
    "Porque la gente no lo veía como algo grave, y las persona se justificaba en que la ciencia es para el avance sin importar los riesgos.",
    "Porque la situación me fue indiferente",
    "Porque lo RegulAr no dan respuesta a las quejas",
    "Porque lo RegulAr no dan respuesta a las quejas",
    "Porque no es algo en lo que yo pueda influir, siento que son cosas que suceden pero no estan en mi campo de acceso ",
    "Porque no es mi deber como persona delatar a alguien, queda en su conciencia y en su habilidad de hacerlo",
    "Porque no hay mecanismos para atender estos temas",
    "Porque no queria quedar como bocón",
    "Porque no se garantizaba mi anonimato y por ende la garantía de no represalias.",
    "Porque no se garantizaba mi anonimato y por ende la garantía de no represalias.",
    "Porque no tenía pruebas suficientes",
    "Porque no tuve la oportunidad de hacerlo ",
    "Porque se ve como una lucha perdida ",
    "Porque se ve como una lucha perdida ",
    "Se logra envidenciar que se ve comprometido el empleo",
    "Se normalizan las cosas así que uno ya lo ve como algo común, o por temor ",
    "Se normalizan las cosas así que uno ya lo ve como algo común, o por temor ",
    "Se normalizan las cosas así que uno ya lo ve como algo común, o por temor ",
    "Si el único que sale perjudicado es quien realiza la falta, no veo relevancia de reportarla",
    "son las mismas estructuras las que lo permiten",
    "Ya habían Sido reportadas ",
  ]);
}); // end am4core.ready()
